-- Combat Depth Update: 4 new troop slots + brewed battle spells on Army
ALTER TABLE "Army"
  ADD COLUMN "bomber" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "imp" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "warlock" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "mender" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "spellHeal" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "spellRage" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "spellBolt" INTEGER NOT NULL DEFAULT 0;
